module.exports = {
	genome: require("./genome").Model,
	enzyme_class_ref:require("./enzyme_class_ref").Model,
	gene_ontology_ref:require("./gene_ontology_ref").Model,
	genome_feature:require("./genome_feature").Model,
	genome_sequence:require("./genome_sequence").Model,
	host_resp:require("./host_resp").Model,
	id_ref:require("./id_ref").Model,
	misc_niaid_sgc:require("./misc_niaid_sgc").Model,
	pathway:require("./pathway").Model,
	pathway_ref:require("./pathway_ref").Model,
	ppi:require("./ppi").Model,
	protein_family_ref:require("./protein_family_ref").Model,
	proteomics_experiment:require("./proteomics_experiment").Model,
	proteomics_peptide:require("./proteomics_peptide").Model,
	proteomics_protein:require("./proteomics_protein").Model,
	sp_gene:require("./sp_gene").Model,
	sp_gene_evidence:require("./sp_gene_evidence").Model,
	sp_gene_ref:require("./sp_gene_ref").Model,
	taxonomy:require("./taxonomy").Model,
	transcriptomics_experiment:require("./transcriptomics_experiment").Model,
	transcriptomics_gene:require("./transcriptomics_gene").Model,
	transcriptomics_sample:require("./transcriptomics_sample").Model
}
